### PR TITLE
Update MetatagsTags.php

### PR DESCRIPTION
**Pull request by bfaulkner-champions**
Removed some requirements for objects which was causing us a fatal error.

### CODE REVIEW

**Comment by adammorland** [comment]
+1

**Comment by gioppy** [comment]
Hi,
thank you for PR. I apologize for the late reply but I am really busy on some projects and I don't have much free time.
On which version of Statamic + Laravel + php did you encounter this error?
I see that with Statamic version 3.3 many things have changed regarding the various fields value, and I had to change the output logic of the values in the template.

**Comment by bfaulkner-champions** [comment]
Hi,

We get it across multiple configurations, but the main thing seems to be Statamic ^3.3. All our sites use PHP ^8.

Kind regards
Ben

[Text  Description automatically generated with low confidence]
Because email can be altered electronically, the integrity of this communication cannot be guaranteed. Any views expressed in this email are personal and should not be taken to represent the views of Champions (UK) plc or its associated companies. The information transmitted is confidential and intended only for use to the individual or entity to which it is addressed. If you have received this communication in error, please contact the sender and delete the material from your computer. This email and the information it contains may be privileged and/or confidential. It is for the intended addressee(s) only. The unauthorised use, disclosure or copying of this email, or any information it contains is prohibited and could in certain circumstances be a criminal offence. If you are not the intended recipient, please notify ***@***.******@***.***> immediately and delete the message from your system. Please note that Champions (UK) plc does not enter into any form of contract by means of Internet email. None of the staff at Champions (UK) plc is authorised to enter into contracts on behalf of the company in this way. All contracts to which Champions (UK) plc is a party are documented by other means. Champions (UK) plc monitors emails to ensure its systems operate effectively and to minimise the risk of viruses.  Whilst it has taken reasonable steps to scan this email, it does not accept liability for any virus that it may contain.


From: Giovanni Buffa ***@***.***>
Date: Sunday, 17 July 2022 at 15:26
To: gioppy/statamic-metatags ***@***.***>
Cc: Ben Faulkner ***@***.***>, Author ***@***.***>
Subject: Re: [gioppy/statamic-metatags] Update MetatagsTags.php (PR #4)
CAUTION EXTERNAL EMAIL:
This Message originated outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.
- Helpdesk
________________________________

Hi,
thank you for PR. I apologize for the late reply but I am really busy on some projects and I don't have much free time.
On which version of Statamic + Laravel + php did you encounter this error?
I see that with Statamic version 3.3 many things have changed regarding the various fields value, and I had to change the output logic of the values in the template.

**Comment by gioppy** [comment]
I have update the package for Statamic 3.3. If you have already installed my package, set this on your `composer.json`
```"gioppy/statamic-metatags": "^2.0.0"```
and run `composer update gioppy/statamic-metatags`.

Please, open an issue if you have other problems or you have some errors.

**Pull request closed without merging**
